on: 
  push:
  workflow_dispatch:
    
env:
  # Image name
  image: srcds-l4d2
  tag: ${{ forgejo.ref_name }}
  user: jackz
  registry: git.jackz.me
  APPID: 222860

jobs:
  build:
    runs-on: ubuntu-full
    steps:
      - name: cache (steamcmd)
        id: cache-steamcmd
        uses: https://git.jackz.me/actions/cache@v5
        with:
          path: steamcmd
          key: steamcmd
      - name: cache (game download)
        id: cache-download
        uses: https://git.jackz.me/actions/cache@v5
        with:
          path: srcds_cache
          key: srcds_cache
      - name: download steamcmd
        if: steps.cache-steamcmd.outputs.cache-hit != 'true'
        run: mkdir steamcmd && curl -fsSL https://media.steampowered.com/client/steamcmd_linux.tar.gz | tar -xz -C steamcmd
      - name: install game (freetodownload fix)
        if: steps.cache-download.outputs.cache-hit != 'true'
        run: steamcmd/steamcmd.sh +@sSteamCmdForcePlatformType windows +force_install_dir "$PWD"/srcds_cache +login anonymous +app_update $APPID +quit
      - name: install game
        run: steamcmd/steamcmd.sh +@sSteamCmdForcePlatformType linux +force_install_dir "$PWD"/srcds_cache +login anonymous +app_update $APPID +quit
      - name: Docker meta
        id: meta
        uses: https://git.jackz.me/actions/docker-metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: ${{ env.registry }}/${{ env.user }}/${{ env.image }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      - name: Login to Container Registry
        uses: https://git.jackz.me/actions/docker-login-action@v3
        with:
          registry: ${{ env.registry }}
          username: ${{ env.user }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - name: Set up Docker Buildx
        uses: https://git.jackz.me/actions/docker-setup-buildx-action@v3
      - name: Build and push
        uses: https://git.jackz.me/actions/docker-build-push-action@v6
        with:
          file: base/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.registry }}/${{ env.user }}/${{ env.image }}:buildcache
          cache-to: type=registry,ref=${{ env.registry }}/${{ env.user }}/${{ env.image }}:buildcache,mode=max